language: android
android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28

before_install:
  - yes | sdkmanager "platforms;android-28" # accept licences automagically

jdk:
  - oraclejdk8

script:
  - ./gradlew assemble

notifications:
  email: false
